baseURL: 
languageCode: en-us
defaultContentLanguage: en
title: Cork OpenCoffee
theme: cupper-hugo-theme
googleAnalytics: 
disqusShortname: 
enableGitInfo: false
publishDir: docs

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Cork OpenCoffee ran from March 2007 until October 2015.
  homeMetaContent: The aim of OCC was to bring together a good mix of entrepreneurs, investors, developers and marketers, plus anyone else who is interested in growing the start-up community in Cork.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to GitHub Pages.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: 
  katex: false
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  logoAlt: "An alternative text description of the logo"
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Attendees
      url: /attendees/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
